<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Email Client for Orchard Core - UI Test Extensions</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2025, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Email Client for Orchard Core - UI Test Extensions: Extension methods that test various features in Lombiq Email Client for Orchard Core. See the project website for detailed documentation.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Email;IMAP;Shouldly;xUnit;UITesting;Testing</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Email-Client</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Email-Client/blob/dev/Lombiq.EmailClient.Tests.UI/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.EmailClient.Samples\Lombiq.EmailClient.Samples.csproj"/>
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\..\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Lombiq.Tests.UI.csproj"/>
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.Tests.UI" Version="14.2.2-alpha.10.osoe-925"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="Readme.md"/>
    <None Include="NuGetIcon.png" Pack="true" PackagePath=""/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="TestEmails\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

</Project>
