name: Validate NuGet Publish

# Temporarily commented out until making it a fully compliant OSS module.
## on:
##   pull_request:
##   push:
##     branches:
##       - dev
## 
## jobs:
##   validate-nuget-publish:
##     name: Validate NuGet Publish
##     uses: Lombiq/GitHub-Actions/.github/workflows/validate-nuget-publish.yml@dev
